travis:
  secure:
    BINSTAR_TOKEN: tW0dfsbILpao06/BtMvFszrkeBKJI9sVT18TaqF0ara74Ka/MyvtcnGh8qeVM1oV3jJukGpPcfeTrvVW4lsA8Bxo4es3dafAv+gt7yhXj6h10TQ+wRiorhy2Q6jRJ9T++H4qxsWR+6SdBU0jbZLb2KSYR8nxQydkLkPxO88643kYMcTuOER7xLDeHgpGflP0v8aBQ4L5Qeyj1LSSNDsOlrXlf/fhs9yMQyJsynzVvWQdtMJgjwm1hCNUFT3wam0intz8THAu/jUNOxcNJuwJm3BBAVCtaC5dqbzZIs+zPgSR5lsEgUDFAKbpa9Pt0l2apYW0c4l1myRR1CaPPSWYf31RG42+aJNvJabz1U/UE3dkkRXoHRm2ncXGev3A5nM8N24qmhCjYeQCBvSp610ZGaR+khBmn0UahJ+JyP1xgBEc8oKp2INv75R/xDF+42R9Kpigu7KfeqjIH3KYLyEdX2RdbZdACjBb+hr2Ken7Fx+SR+FQ1bwFQIAeZDYWnah0POZp9DPtSntJsljsRg1L4nzMM6lFeZdYTvzsmYlreEVyu3I1wK0frT/aRHcZpyVy7xFkH6iyJCoBQrh+FVSD8arRAxZxI7ssowp1ZVBkmWfspYnCCE6Rj56VuwUiJVB/EvWcMzv1n2qAXtJNs8IavYz+keZG5zulHHlqzxnC/7s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
