travis:
  secure:
    BINSTAR_TOKEN: Pp9yXHF8asc0q0eLVxIWYcYbQLzPwRVBBx7Jg6sY7CE3ho39aQ/zyeidTiTTul0HS/1pHR7igGBMmR9PORb7UqLtmgDB4v3bcOmslZzeOY+OZlgX9SYf+im1p+SEzyBTYMXK+RuKhItOtTqgsurbSHEg6UeOKIkXBsiju/PdXhdwpOZKexu3+MU9Fi/4BqeIFnv0uucHyrbPOX9kZkNIMdkhZxFALbcFy9fJIA5NnL1qIXMEW28NOBZhm5vsg73lsjEWQHUt7U/5Jr+X7EfGTtfKhkNpdXesRETVhcyHMVklrKvtE8/0Vq9Q22AROCivfLG1gTby33dF94PHmqoPep97NUnh5DcP13pMRJgJ9+X44n/ZodYYWQDxQSgtwufTMtLohCa/WEY3VdNhClt0h0+JW93OEPo+wg5XUIppJdIAbVQzcbxJT/zSpghlhyx+eWFNGNCNRl5asspZmRu46wen84nZrUI6v0B0EyO57byL3U4QAgr+4D3YPAkJq3qXKRmucq899J9mEy7Nf18C4bmI1WtkWjYsmWRrreZWErTIjxICf9+SJsAmyyUQCMzN4YBI/B04+QImC9FbuCVyBLXbabJkdT71xz53g3VgzFPBdXrYZeZtLpaZm5dWQ0K/M9uHaTdmXzQIPqQEwrWVRBaqX7yGdgON8wjq8qiomNc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
