appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PR+inxxK8B+/99PRV2SFz91yV/swozaME95rP0ymBGGzg0YkVvDVY14xcVEhzQ+OfFnoscAc+n16vYJs58iSoRIZTlJGf5TSjfZVQ1VxpUATiC4pQNJcEV/zqhfOjmHK5VpvSXaTwSvsoiKhx37KjcGpGfvsNma8CXEEVVDTm36oSStMDNN1hLZah977JJTSDEzsbry8TkSQ+k0GncE2OOdPY83jG7ikcAFef7EGvHF4NsxuTgJwSOkzQqUufg1Z/RznS/5hlGDghDCNqfSpD3ziAR+EH2v15W8F1MmhoT8OD4WUyXy7HDfMctRrZk1byqzLlhhDg9uETmU64qMfjLFiRgcmunEDnj+11etBarddA7x1ORlb9S40FOY3mgbeIjkM8KnUWJQ3s5pVG2khWQ5PX/v5TAaZtdVtYAyj4iTtuExIP/SEqGUVokplkP2XL7mVXOFj82AFZk3W5rDfmggBUdzMY1kmTcwa0BRF5dEJ6bXexQ8quQAhOV547EpQ8KSTb74AUsUeaVzyRmIaqiw2VTtVCyKV5p7sV0Y30i2HRYlhu5EqNFsOyUui0BVaqB7WDRONAyHWebv80Zh3S8Gmrb6GeuSf3ikxJ28dSA5an1kH7ptH3zcakMU7WD5XMPrNqHDuH7J0bSTtxWRDgrfxMPjBabQdazTv3HVoJv4=
