travis:
  secure:
    BINSTAR_TOKEN: RBxrhglNdO5k+aWu38r0ZGvcZo3WM9uS/JKeTPKMTBF8e+F7tsyzsU7ldgKXSdWGJMt1EuOLFdtAM+jtKM58RPnBrQ7tv7W2HspAxrRvuZHLy70VjpJY6OQh6Mvfq82smlx8+3l49zyffhn3fvuqTVjDg+IofX5cekkOTMFfQCY/CJTjEUQMvhtFDH3s7CNxxijaoaXiQ5hNrwo4ICCmmEyWBZeKSa9e4Igd3ivjJVyBU0NgZmYHXZTNREcN7wPgDDM2FlNrxl52+CL7BPLxNsg6Af8JVcEPN3q2zREYz8mMVmLYrbBsU1LYzWIYBj3OShvk+mn2S1e2CJ73RmAJN0t2UuPL3KJrj6U/TFamkkIo/CIXrDBMauJcKwMylJlIYgCX1wIca4K8yH/hybnqSn8aVHXw+y2dCrcPbjeqzFxLGOkcYsDKkEQk/Y8vSZYvfWvfHpMAIzfcZIhiZWpC97R27TRAj4NT7CC0gEySfrxz7ElpRxRU2UzTT9/KVZ/ICBzSCDxyHqssoAFzJV4NdC+TbiihrecDwOVLW9SmlIJ6C0Ez0o3bPb/nhH9lcqM0KoNYA7NYd1OJnaB3uiBqwooyid6VPBLngN51I3PYgV7pnDeim59p5Nz2heZvBgwg4BnUmu7KneenVdeLjhrKSrOVx2qMHlWgSSJG+WYT9WQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
